version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # Semelhante ao FROM do Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always # Garante que qunado alterar o arquivo n necessite dar comandos extras
    environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: rhuan
        MYSQL_PASSWORD: secret

  wordpress:
    depends_on: # Serviços que esse cointainer depende
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: rhuan
        WORDPRESS_DB_PASSWORD: secret
        WORDPRESS_DB_NAME: wordpress
volumes:
  db_data:

