version: '3.3'

services:
  db: # Container de MySQL
    image: mysql:5.7 # Semelhante ao FROM do Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always # Garante que qunado alterar o arquivo n necessite dar comandos extras
    env_file:
      - ./config/db.env

  wordpress:
    depends_on: # Serviços que esse cointainer depende
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
        
volumes:
  db_data:

